// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:908218167103:web:23986f025b2df3fb6c2d8a',
    messagingSenderId: '908218167103',
    projectId: 'e-commerce-af11c',
    authDomain: 'e-commerce-af11c.firebaseapp.com',
    storageBucket: 'e-commerce-af11c.firebasestorage.app',
    measurementId: 'G-DK6B51X5JV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:908218167103:android:edd2dae1ee29ad586c2d8a',
    messagingSenderId: '908218167103',
    projectId: 'e-commerce-af11c',
    storageBucket: 'e-commerce-af11c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:908218167103:ios:cff5ab18796d9e6c6c2d8a',
    messagingSenderId: '908218167103',
    projectId: 'e-commerce-af11c',
    storageBucket: 'e-commerce-af11c.firebasestorage.app',
    iosClientId:
        '908218167103-3343vaenhvmoi4cmkfpqkod7ekvb7k8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:908218167103:ios:cff5ab18796d9e6c6c2d8a',
    messagingSenderId: '908218167103',
    projectId: 'e-commerce-af11c',
    storageBucket: 'e-commerce-af11c.firebasestorage.app',
    iosClientId:
        '908218167103-3343vaenhvmoi4cmkfpqkod7ekvb7k8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.store',
  );
}
